### PR TITLE
Fixed planet generation etc.

### PR DESCRIPTION
**Pull request by iffa**
Decided to help you out with the project. I've written pretty detailed commit messages so you can read those before merging this request. But here are the changes in a nutshell:
- Fixed planet generation for real (read more about it in my last two commits), **confirmed to be working**
- In the process I broke the /space enter/exit/list commands (see my last commit msg for more info and a stacktrace) - **oops :D**
- Changed anything (I hope) bSpace -> CrystalSpace, it is the new name after all (permissions.. configs... some variables were also still using bSpace, which may have caused issues later on)
- Other changes I probably forget now

I hope this helps you guys out! There are still some old features that are deprecated/useless in the code, and it could use a good cleanup (especially the configs) - but there isn't any hurry. :)

### CODE REVIEW

**Comment by immaterial-ctrl** [comment]
Awesome!! You fixed some things that would have probably taken us ages to figure, given we don't know the ins and outs of this beast yet - merging pull request.

**Comment by justwheel** [comment]
Agreed, like @Jacc734 said, some of these things would have probably taken us forever to figure out on our own! Thanks so much for your contribution; it is greatly appreciated!

Also, @iffa, if you are interested in picking up this project again, the rest of the team and myself communicate privately on a platform called Slack. If you would be interested in joining our discussions, please let me know and I'd be happy to add you to our Slack group so we can work together on this! If not, I also understand as well, and I am still appreciative of your help so far!

**Comment by iffa** [comment]
Hmm.. @jflory7, I can definitely join your discussions to help out - I'm not sure as to how much help I can provide you codewise as my time is pretty limited these days, but I can give pointers for sure. Hit me up! :+1:

**Comment by justwheel** [comment]
@iffa 
Awesome! And that's completely understandable about being busy. Anything you can contribute will always be welcome! I'll just need your email to add you to our Slack!

**Comment by iffa** [comment]
@jflory7 iffa[at]crappy.email

**Comment by justwheel** [comment]
@iffa Just emailed you the invite.

**Pull request merged**
